-----------------------------------------------  🌲  | master -----------------------------------------------

diff --git a/prepare-commit-msg b/prepare-commit-msg
--- a/prepare-commit-msg
+++ b/prepare-commit-msg
@@ -4,10 +4,55 @@
 # This hook will extract meta info from the system and push
 # it as a comment in the commit
 #
-# Currently Supported: Git Branch Info, Spotify Current Track
+#
 #
 # To enable this hook, rename this file to "prepare-commit-msg".
 #
+
+# prepare-commit-msg
+# This hook is invoked by git-commit[1] right after preparing the default log message, and before the editor is started.
+
+# It takes one to three parameters.
+# The first is the name of the file that contains the commit log message.
+# The second is the source of the commit message,
+#	and can be: message (if a -m or -F option was given);
+#	template (if a -t option was given or the configuration option commit.template is set);
+#	merge (if the commit is a merge or a .git/MERGE_MSG file exists);
+#	squash (if a .git/SQUASH_MSG file exists);
+#	or commit,
+# followed by a commit SHA-1 (if a -c, -C or --amend option was given).
+
+# If the exit status is non-zero, git commit will abort.
+
+# The purpose of the hook is to edit the message file in place, and it is not suppressed by the --no-verify option. A non-zero exit means a failure of the hook and aborts the commit. It should not be used as replacement for pre-commit hook.
+
+# The sample prepare-commit-msg hook that comes with Git removes the help message found in the commented portion of the commit template.
+
+#!/bin/bash
+
+# programname=$0
+
+# function usage {
+#     echo "usage: $programname [-abch] [-f infile] [-o outfile]"
+#     echo "  -a      turn on feature a"
+#     echo "  -b      turn on feature b"
+#     echo "  -c      turn on feature c"
+#     echo "  -h      display help"
+#     echo "  -f infile   specify input file infile"
+#     echo "  -o outfile  specify output file outfile"
+#     exit 1
+# }
+
+# usage
+
+if [ $# -eq 0 ]
+  then
+    echo "No arguments supplied!" && exit 0
+fi
+
+echo "$(cat $1)"
+echo "$2"
+echo "$3"
 
 # Succeed on all merge messages, as evidenced by MERGE_MSG existing
 [ -f $GIT_DIR/MERGE_MSG ] && exit 0
